# Site settings
title: Dr. Qazi Mazhar ul Haq
#twitter_username: QaziMazhar_
name: Dr. Qazi Mazhar ul Haq

# Build settings
#markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
#  - title: Blog
#    url: http://technologination.blogspot.com/
 - title: GitHub
   url: https://github.com/Dr-qazi
 - title: LinkedIn
   url: https://www.linkedin.com/in/qazi-mazhar/
 - title: Facebook
   url: https://www.facebook.com/qazi.mazhar2
 - title: Twitter
   url: https://twitter.com/QaziMazhar_
 - title: Google Scholar
   url: https://scholar.google.com/citations?user=AeJN-sYAAAAJ&hl=en
 - title: ResearchGate
   url: https://www.researchgate.net/profile/Qazi-Mazhar

#Any buzzword skills you want to include
skills:
 
 - MATLAB
 - OpenCV
 - Python
 - PyTorch
 - Tensorflow
 




#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: Previous Research

#Work experience is required
additionalinfo: |
   <p style="font-size:14px;"><strong>Year</strong>: Aug 2023 - July 2024 <br/>
   <strong>Office</strong>: Yuan Ze University, Taiwan<br/>
   <strong>Position</strong>: Assistant Professor <br/>
   <strong>Subject</strong>: During this position i am teaching subject Calculus-I and Introduction to Computer Science<br/>
   </p>
   <p style="font-size:14px;"><strong>Year</strong>: September 2022- July 2023 <br/>
   <strong>Office</strong>: National University of Sciences and Technology, Pakistan<br/>
   <strong>Position</strong>: Assistant Professor <br/>
   <strong>Subject</strong>:  During this position i was teaching computer software engineering subjects such as Data Structure and Analaysis, Design and Analysis of Algorithms<br/>
   </p>
   <p style="font-size:14px;"><strong>Year</strong>: Dec 2021 - Aug 2022 <br/>
   <strong>Office</strong>: National Taipei University of Technology (NTUT), Taiwan<br/>
   <strong>Position</strong>: Postdoctoral Researcher <br/>
   <strong>Subject</strong>: During this position i was mainly involved in writing manuscript of high impact journals. Research areas include Anamoly detection, Autonomous Vehicles, Person Re-identification.<br/>
   </p>

# roles:
# - title: Assistant Professor
#   start: Aug 2023
#   end: July 2024
#   employer: Yuan Ze University, Taiwan
#   description: During this position i am teaching subject Calculus-I and Introduction to Computer Science
# - title: Assistant Professor
#   start: Sep 2022
#   end: July 2022
#   employer: National University of Sciences and Technology, Pakistan
#   description: During this position i was teaching computer software engineering subjects such as Data Structure and Analaysis, Design and Analysis of Algorithms
# - title: Postdoctoral Researcher
#   start: Jan 2022
#   end: Aug 2022
#   employer: National Taipei University of Technology, Taiwan
#   description: During this position i was mainly involved in writing manuscript of high impact journals. Research areas include Anamoly detection, Autonomous Vehicles, Person Re-identification.

#Education is required
education:
 - level: (Ph.D.)
   date: 2021
   dept: Electronic and Computer Engineering
   subject: (Computer Vision and Artificial Intelligence)
   school: National Taiwan University of Science and Technology
 - level: (MS)
   date: 2016
   dept: Electrical Engineering
   subject: (Digital Image Processing and Computer Vision)
   school: National University of Sciences and Technology Islamabad, Pakistan
 - level: (B.E/BEng) 
   date: 2014
   dept: Telecommunication Engineering
   subject: (Signal and Image Pocessing)
   school: University of Engineeirng and Technology Peshawar
 - level: (B.E/BEng) (Quit)
   date: 2009-2010
   dept: Electrical (Telecommunication) Engineering
   subject: (Signal and Image Pocessing)
   school: Kohat University of Science and Technology.

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    talks:
#     - title: Menggapai Mimpi di Kancah Internasional
#       host: Universitas Internasional Semen Indonesia (UISI)
#       date: July 4, 2020
#    talks2:
#     - title: Artificial Intelligence Applications in Real-Life
#       host: Sekolah Tinggi Teknologi Bandung (STTB)
#       date: July 10, 2021
#    talks3:
#     - title: When Remote Sensing Meets Artificial Intelligence 
#       host: Universitas Negeri Makasar (UNM)
#       date: December 4, 2021

#List of interesting Github repo/projects to include - optional
#github:
# - wahyurahmaniar/wahyurahmaniar.github.io

#This section is optional (as is the image link below)
coursera: Awards

#Stackoverflow flair is optional
stackoverflow: Resume
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  <p style="font-size:15px;">
  
  Dr. Qazi Mazhar ul Haq is currently working as Assisstant Professor in Department of International Beachlor Program in Informatics and Computer Science and Engineering at Yuan Ze University Taiwan. He holds a PhD in Electronics and Computer Engineering from the National Taiwan University of Science and Technology. His research interests include object detection, incremental learning, anomaly detection, image processing, deep learning, as well as the 3D object detection. He is currently working on Autonomous robots for automatic delivery in hopsitals. Qazi will be conducting autonomous tri-cycle upon completion of his current projects.
  <br/><br/>
  </p>
  <p style="color:blue "align="right">~Qazi~</p>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
# additionalinfo: |
#    <p style="font-size:14px;"><strong>Year</strong>: November 2021 - now <br/>
#    <strong>Office</strong>: National Taipei University of Technology (NTUT), Taiwan<br/>
#    <strong>Position</strong>: Postdoctoral Researcher <br/>
#    <strong>Subject</strong>: computer vision, image processing, artificial intelligence <br/>
#    </p>

#    <p style="font-size:14px;"><strong>Year</strong>: Jan 2019 - Dec 2020 <br/>
#    <strong>Office</strong>: Industrial Technology Research Institute, Hsinchu, Taiwan <br/>
#    <strong>Position</strong>: Research Associate <br/>
#    <strong>Subject</strong>: Object detection for delf-driving cars <br/>
#    </p>
 
